# fly.toml app configuration file generated for smart-resume on 2025-11-10T10:37:33+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'smart-resume'
primary_region = 'bom'

[build]

[deploy]
  strategy = 'rolling'
  wait_timeout = '10m0s'

[env]
  DEBUG = 'false'
  LOG_LEVEL = 'info'

[[mounts]]
  source = 'ml_models_vol'
  destination = '/app/models'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '2m0s'
    timeout = '30s'
    grace_period = '1m0s'
    method = 'GET'
    path = '/api/v1/health'

[[vm]]
  memory = '8gb'
  cpu_kind = 'shared'
  cpus = 8
